const std = @import("std");
const Dir = std.Io.Dir;
const File = std.Io.File;

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const gpa = init.gpa;

    const templates_path = "templates";
    const out_path = "src/cli/embedded_templates.zig";

    const cwd = Dir.cwd();
    var templates_dir = cwd.openDir(io, templates_path, .{ .iterate = true }) catch |err| {
        std.debug.print("error: cannot open templates dir '{s}': {s}\n", .{ templates_path, @errorName(err) });
        std.process.exit(1);
    };
    defer templates_dir.close(io);

    var template_names = std.ArrayList([]const u8).empty;
    defer {
        for (template_names.items) |n| gpa.free(n);
        template_names.deinit(gpa);
    }

    var template_file_list = std.StringHashMap(std.ArrayList([]const u8)).init(gpa);
    defer {
        var it = template_file_list.iterator();
        while (it.next()) |entry| {
            for (entry.value_ptr.items) |f| gpa.free(f);
            entry.value_ptr.deinit(gpa);
        }
        template_file_list.deinit();
    }

    var templates_iter = templates_dir.iterate();
    while (templates_iter.next(io) catch null) |entry| {
        if (entry.kind != .directory) continue;
        if (isBuildArtifact(entry.name)) continue;

        const name = try gpa.dupe(u8, entry.name);
        try template_names.append(gpa, name);

        const tmpl_dir = templates_dir.openDir(io, entry.name, .{ .iterate = true }) catch continue;
        defer tmpl_dir.close(io);

        var files = std.ArrayList([]const u8).empty;
        try collectTemplateFiles(io, &tmpl_dir, "", gpa, &files);
        try template_file_list.put(name, files);
    }

    if (template_names.items.len == 0) {
        std.debug.print("error: no templates found in '{s}'\n", .{templates_path});
        std.process.exit(1);
    }

    var source = std.ArrayList(u8).empty;
    defer source.deinit(gpa);

    try source.appendSlice(gpa,
        "// This file is auto-generated by build.zig.\n" ++
        "// Do not edit manually — run `zig build` to regenerate.\n" ++
        "const std = @import(\"std\");\n" ++
        "\n" ++
        "pub const TemplateFile = struct {\n" ++
        "    path: []const u8,\n" ++
        "    content: []const u8,\n" ++
        "};\n" ++
        "\n" ++
        "pub const embedded_template_names = [_][]const u8{\n",
    );

    for (template_names.items) |name| {
        try source.appendSlice(gpa, "    \"");
        try source.appendSlice(gpa, name);
        try source.appendSlice(gpa, "\",\n");
    }
    try source.appendSlice(gpa, "};\n\n");
    try source.appendSlice(gpa, "pub fn getFiles(name: []const u8) ?[]const TemplateFile {\n");

    for (template_names.items) |name| {
        try source.appendSlice(gpa, "    if (std.mem.eql(u8, name, \"");
        try source.appendSlice(gpa, name);
        try source.appendSlice(gpa, "\")) {\n");
        try source.appendSlice(gpa, "        return &[_]TemplateFile{\n");

        const tmpl_dir = templates_dir.openDir(io, name, .{ .iterate = true }) catch continue;
        defer tmpl_dir.close(io);

        const files = template_file_list.get(name).?;
        for (files.items) |file_path| {
            // Read and escape file contents
            const content = tmpl_dir.readFileAlloc(io, file_path, gpa, .limited(1024 * 1024)) catch {
                std.debug.print("warning: could not read {s}/{s}\n", .{ name, file_path });
                continue;
            };
            defer gpa.free(content);

            try source.appendSlice(gpa, "            .{ .path = \"");
            try source.appendSlice(gpa, file_path);
            try source.appendSlice(gpa, "\", .content = \"");

            try writeEscapedString(gpa, &source, content);

            try source.appendSlice(gpa, "\" },\n");
        }

        try source.appendSlice(gpa, "        };\n");
        try source.appendSlice(gpa, "    }\n");
    }

    try source.appendSlice(gpa, "    return null;\n");
    try source.appendSlice(gpa, "}\n");

    const file = cwd.createFile(io, out_path, .{}) catch |err| {
        std.debug.print("error: failed to create '{s}': {s}\n", .{ out_path, @errorName(err) });
        std.process.exit(1);
    };
    defer file.close(io);
    try file.writeStreamingAll(io, source.items);
}

fn writeEscapedString(gpa: std.mem.Allocator, buf: *std.ArrayList(u8), bytes: []const u8) !void {
    for (bytes) |b| {
        switch (b) {
            '\\' => try buf.appendSlice(gpa, "\\\\"),
            '"' => try buf.appendSlice(gpa, "\\\""),
            '\n' => try buf.appendSlice(gpa, "\\n"),
            '\r' => try buf.appendSlice(gpa, "\\r"),
            '\t' => try buf.appendSlice(gpa, "\\t"),
            0, 1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 14...31, 127 => {
                try buf.appendSlice(gpa, "\\x");
                try buf.appendSlice(gpa, &[2]u8{ hex(@as(u4, @truncate(b >> 4))), hex(@as(u4, @truncate(b & 0xf))) });
            },
            else => try buf.appendSlice(gpa, &[1]u8{b}),
        }
    }
}

fn hex(v: u4) u8 {
    return if (v < 10) @as(u8, '0') + v else @as(u8, 'a') + v - 10;
}

fn collectTemplateFiles(io: std.Io, dir: *const Dir, prefix: []const u8, gpa: std.mem.Allocator, files: *std.ArrayList([]const u8)) !void {
    var iter = dir.iterate();
    while (iter.next(io) catch null) |entry| {
        if (entry.kind == .file) {
            if (isBuildArtifact(entry.name)) continue;
            const path = if (prefix.len > 0)
                try std.fs.path.join(gpa, &.{ prefix, entry.name })
            else
                try gpa.dupe(u8, entry.name);
            try files.append(gpa, path);
        } else if (entry.kind == .directory) {
            if (isBuildArtifact(entry.name)) continue;
            const sub_dir = dir.openDir(io, entry.name, .{ .iterate = true }) catch continue;
            defer sub_dir.close(io);
            const sub_prefix = if (prefix.len > 0)
                try std.fs.path.join(gpa, &.{ prefix, entry.name })
            else
                try gpa.dupe(u8, entry.name);
            defer gpa.free(sub_prefix);
            try collectTemplateFiles(io, &sub_dir, sub_prefix, gpa, files);
        }
    }
}

fn isBuildArtifact(name: []const u8) bool {
    return std.mem.eql(u8, name, ".zig-cache") or std.mem.eql(u8, name, "zig-out");
}
