name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.17.0-dev.857+2b2b85c5f
      - run: zig build test --summary all
      - run: zig build test-io-clean
      - run: zig fmt --check .
